// Sons & Co. Canonical Product Dataset (Fully Audited & Verified)
const products = [
    // ==========================================
    // MEN (Gentlemen)
    // ==========================================
    {
        id: 1,
        title: "Tailored Italian Tuxedo Suit",
        category: "men",
        subcategory: "formals",
        season: "winter",
        price: 249.00,
        originalPrice: 399.00,
        image: "https://images.unsplash.com/photo-1593032465175-481ac7f401a0?q=80&w=600&auto=format&fit=crop",
        description: "Exquisitely tailored wool tuxedo jacket and trousers. Features satin peak lapels, a double vent back, and a modern slim silhouette perfect for black-tie affairs.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Premium"
    },
    {
        id: 2,
        title: "Oxford Cotton Dress Shirt",
        category: "men",
        subcategory: "formals",
        season: "spring",
        price: 59.00,
        originalPrice: 89.00,
        image: "https://images.unsplash.com/photo-1620012253295-c05518e99309?q=80&w=600&auto=format&fit=crop",
        description: "Classic white dress shirt woven from long-staple Egyptian cotton. Features a semi-spread collar, double cuffs, and easy-iron finish.",
        sizes: ["M", "L", "XL"],
        badge: "Best Seller"
    },
    {
        id: 3,
        title: "Executive Wool Formal Trousers",
        category: "men",
        subcategory: "formals",
        season: "winter",
        price: 89.00,
        originalPrice: 139.00,
        image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=600&auto=format&fit=crop",
        description: "Sharp pleated formal trousers tailored from breathable worsted wool. Designed for immaculate boardroom presence.",
        sizes: ["30", "32", "34", "36", "38"],
        badge: "Tailored"
    },
    {
        id: 4,
        title: "Modern Fit Navy Suit",
        category: "men",
        subcategory: "formals",
        season: "spring",
        price: 229.00,
        originalPrice: 350.00,
        image: "https://images.unsplash.com/photo-1598808503742-dd34bd0444d9?q=80&w=600&auto=format&fit=crop",
        description: "Versatile navy blue suit in a modern slim fit. Ideal for weddings, formal office days, and special events.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Classic"
    },
    {
        id: 5,
        title: "French Cuff Formal Shirt",
        category: "men",
        subcategory: "formals",
        season: "winter",
        price: 65.00,
        originalPrice: 95.00,
        image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=600&auto=format&fit=crop",
        description: "Premium white formal shirt with double cuffs for cufflinks. High-thread count cotton for a silky feel.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Luxury"
    },
    {
        id: 6,
        title: "Slim-Fit Indigo Denim Jeans",
        category: "men",
        subcategory: "jeans",
        season: "spring",
        price: 79.00,
        originalPrice: 120.00,
        image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=600&auto=format&fit=crop",
        description: "Premium indigo dyed stretch denim. Structured with double-stitched seams and a classic 5-pocket design that ages beautifully with wash.",
        sizes: ["S", "M", "L", "XL"],
        badge: "New"
    },
    {
        id: 7,
        title: "Ripped Light Wash Denim Jeans",
        category: "men",
        subcategory: "jeans",
        season: "summer",
        price: 69.00,
        originalPrice: 110.00,
        image: "https://images.unsplash.com/photo-1617137968427-85924c800a22?q=80&w=600&auto=format&fit=crop",
        description: "Casual light wash denim featuring custom distressing and knee rips. Spun with 2% elastane for comfortable everyday street styling.",
        sizes: ["M", "L", "XL"],
        badge: "Streetwear"
    },
    {
        id: 8,
        title: "Classic Straight-Fit Dark Wash Jeans",
        category: "men",
        subcategory: "jeans",
        season: "winter",
        price: 85.00,
        originalPrice: 130.00,
        image: "https://images.unsplash.com/photo-1582562124811-c09040d0a901?q=80&w=600&auto=format&fit=crop",
        description: "Timeless straight-cut denim in deep rinse indigo. Comfortable through the thigh with a traditional leg opening.",
        sizes: ["30", "32", "34", "36", "38"],
        badge: "Classic"
    },
    {
        id: 9,
        title: "Black Tapered Stretch Jeans",
        category: "men",
        subcategory: "jeans",
        season: "winter",
        price: 82.00,
        originalPrice: 125.00,
        image: "https://images.unsplash.com/photo-1604176354204-9268737828e4?q=80&w=600&auto=format&fit=crop",
        description: "Sleek overdyed black denim with tapered legs and comfortable 4-way stretch resilience.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Modern"
    },
    {
        id: 10,
        title: "Grey Stone-Washed Jeans",
        category: "men",
        subcategory: "jeans",
        season: "spring",
        price: 75.00,
        originalPrice: 115.00,
        image: "https://images.unsplash.com/photo-1602293589930-45aad59ba3ab?q=80&w=600&auto=format&fit=crop",
        description: "Rugged stone-washed grey denim with reinforced stitching for long-lasting wear.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Rugged"
    },
    {
        id: 11,
        title: "Classic Cotton Chino Shorts",
        category: "men",
        subcategory: "shorts",
        season: "summer",
        price: 39.00,
        originalPrice: 59.00,
        image: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?q=80&w=600&auto=format&fit=crop",
        description: "Essential chino shorts crafted from premium cotton twill with a touch of stretch. Featuring a tailored fit and side pockets.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Essential"
    },
    {
        id: 12,
        title: "Rugged Cargo Shorts",
        category: "men",
        subcategory: "shorts",
        season: "spring",
        price: 45.00,
        originalPrice: 65.00,
        image: "https://images.unsplash.com/photo-1625910514393-775518b76776?q=80&w=600&auto=format&fit=crop",
        description: "Durable cargo shorts designed for outdoor adventure. Featuring six utility pockets and reinforced seams.",
        sizes: ["M", "L", "XL"],
        badge: "Utility"
    },
    {
        id: 13,
        title: "Athletic Performance Shorts",
        category: "men",
        subcategory: "shorts",
        season: "summer",
        price: 35.00,
        originalPrice: 50.00,
        image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=600&auto=format&fit=crop",
        description: "Lightweight, moisture-wicking shorts with built-in liner. Perfect for running and training.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Athletic"
    },
    {
        id: 14,
        title: "Lounge Knit Shorts",
        category: "men",
        subcategory: "shorts",
        season: "spring",
        price: 29.00,
        originalPrice: 40.00,
        image: "https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?q=80&w=600&auto=format&fit=crop",
        description: "Ultra-soft cotton blend knit shorts perfect for relaxing at home or casual outings.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Cozy"
    },
    {
        id: 15,
        title: "Relaxed Fit Denim Shorts",
        category: "men",
        subcategory: "shorts",
        season: "summer",
        price: 55.00,
        originalPrice: 85.00,
        image: "https://images.unsplash.com/photo-1479064555552-3ef4979f8908?q=80&w=600&auto=format&fit=crop",
        description: "Structured denim shorts with a classic washed look. Features 5-pocket styling and comfortable cut.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Classic"
    },
    {
        id: 16,
        title: "Linen Summer Short Sleeve Shirt",
        category: "men",
        subcategory: "casuals",
        season: "summer",
        price: 45.00,
        originalPrice: 79.00,
        image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=600&auto=format&fit=crop",
        description: "Woven from lightweight, breathable French flax linen. Ideal for hot summer days, featuring a casual Cuban collar.",
        sizes: ["M", "L", "XL"],
        badge: "Summer Edit"
    },
    {
        id: 17,
        title: "Organic Cotton Crewneck T-Shirt",
        category: "men",
        subcategory: "casuals",
        season: "summer",
        price: 29.00,
        originalPrice: 45.00,
        image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=600&auto=format&fit=crop",
        description: "Supima cotton everyday crewneck t-shirt. Pre-shrunk and tailored for a clean, non-boxy fit.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Essential"
    },
    {
        id: 18,
        title: "Pique Cotton Polo Shirt",
        category: "men",
        subcategory: "casuals",
        season: "spring",
        price: 42.00,
        originalPrice: 65.00,
        image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?q=80&w=600&auto=format&fit=crop",
        description: "Breathable cotton pique polo with ribbed collar and clean two-button placket.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Smart Casual"
    },
    {
        id: 19,
        title: "Chambray Button-Down Shirt",
        category: "men",
        subcategory: "casuals",
        season: "spring",
        price: 49.00,
        originalPrice: 72.00,
        image: "https://images.unsplash.com/photo-1603252109303-2751441dd157?q=80&w=600&auto=format&fit=crop",
        description: "Versatile indigo chambray shirt that bridges the gap between formal and casual attire.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Versatile"
    },
    {
        id: 20,
        title: "Casual Cotton Chinos",
        category: "men",
        subcategory: "casuals",
        season: "spring",
        price: 68.00,
        originalPrice: 95.00,
        image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=600&auto=format&fit=crop",
        description: "Tailored chinos in premium cotton twill. Perfect for everyday smart-casual wear.",
        sizes: ["30", "32", "34", "36"],
        badge: "Everyday"
    },
    {
        id: 21,
        title: "Wool Blend Overcoat",
        category: "men",
        subcategory: "winter",
        season: "winter",
        price: 189.00,
        originalPrice: 280.00,
        image: "https://images.unsplash.com/photo-1544923246-77307dd654cb?q=80&w=600&auto=format&fit=crop",
        description: "Elegant long-line overcoat crafted from a warm wool blend. Features a structured collar and internal pockets.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Winter Warmth"
    },
    {
        id: 22,
        title: "Cable Knit Wool Sweater",
        category: "men",
        subcategory: "winter",
        season: "winter",
        price: 85.00,
        originalPrice: 120.00,
        image: "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?q=80&w=600&auto=format&fit=crop",
        description: "Classic cable knit sweater in pure lambswool. Thick, warm, and timeless.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Cozy"
    },
    {
        id: 23,
        title: "Puffer Down Jacket",
        category: "men",
        subcategory: "winter",
        season: "winter",
        price: 145.00,
        originalPrice: 210.00,
        image: "https://images.unsplash.com/photo-1548883354-7622d03aca27?q=80&w=600&auto=format&fit=crop",
        description: "Water-resistant puffer jacket filled with ethically sourced down for extreme cold protection.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Outdoor"
    },
    {
        id: 24,
        title: "Merino Wool Cardigan",
        category: "men",
        subcategory: "winter",
        season: "winter",
        price: 95.00,
        originalPrice: 140.00,
        image: "https://images.unsplash.com/photo-1611312449412-6ce0a63e46ea?q=80&w=600&auto=format&fit=crop",
        description: "Fine-gauge merino wool cardigan. A perfect layering piece for smart-winter looks.",
        sizes: ["S", "M", "L", "XL"],
        badge: "New Arrival"
    },
    {
        id: 25,
        title: "Leather Bomber Jacket",
        category: "men",
        subcategory: "winter",
        season: "winter",
        price: 210.00,
        originalPrice: 320.00,
        image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=600&auto=format&fit=crop",
        description: "Premium leather bomber jacket with ribbed cuffs and hem. A rugged winter essential.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Premium"
    },
    {
        id: 26,
        title: "Embroidered Silk Kurta",
        category: "men",
        subcategory: "ethnic",
        season: "spring",
        price: 85.00,
        originalPrice: 130.00,
        image: "https://images.unsplash.com/photo-1608748010899-18f300247112?q=80&w=600&auto=format&fit=crop",
        description: "Elegant silk-blend kurta with intricate hand-embroidery on the collar and placket.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Festive"
    },
    {
        id: 27,
        title: "Cotton Printed Kurta Set",
        category: "men",
        subcategory: "ethnic",
        season: "summer",
        price: 65.00,
        originalPrice: 95.00,
        image: "https://images.unsplash.com/photo-1600054800743-be066272c0e5?q=80&w=600&auto=format&fit=crop",
        description: "Comfortable cotton kurta with traditional prints, paired with matching pajama pants.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Everyday"
    },
    {
        id: 28,
        title: "Designer Wedding Sherwani",
        category: "men",
        subcategory: "ethnic",
        season: "winter",
        price: 299.00,
        originalPrice: 450.00,
        image: "https://images.unsplash.com/photo-1605518216991-7c220f49a201?q=80&w=600&auto=format&fit=crop",
        description: "Regal sherwani featuring rich zari work and a structured silhouette for grand occasions.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Wedding Wear"
    },
    {
        id: 29,
        title: "Modi Jacket (Nehru Vest)",
        category: "men",
        subcategory: "ethnic",
        season: "spring",
        price: 55.00,
        originalPrice: 85.00,
        image: "https://images.unsplash.com/photo-1611601679655-7c8bc197f0c6?q=80&w=600&auto=format&fit=crop",
        description: "Tailored Nehru vest in textured khadi fabric. Perfect for layering over kurtas.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Versatile"
    },
    {
        id: 30,
        title: "Linen Long Kurta",
        category: "men",
        subcategory: "ethnic",
        season: "summer",
        price: 72.00,
        originalPrice: 110.00,
        image: "https://images.unsplash.com/photo-1618244972963-dbee1a7edc95?q=80&w=600&auto=format&fit=crop",
        description: "Minimalist long kurta crafted from premium pure linen. Breathable and stylish.",
        sizes: ["M", "L", "XL"],
        badge: "Summer Edit"
    },
    {
        id: 31,
        title: "Men's Classic Striped Pajama Set",
        category: "men",
        subcategory: "pajamas",
        season: "winter",
        price: 49.00,
        originalPrice: 69.00,
        image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?q=80&w=600&auto=format&fit=crop",
        description: "Supremely comfortable organic cotton pajama set with a classic vertical stripe pattern.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Sleepwear"
    },
    {
        id: 32,
        title: "Flannel Loungewear Bottoms",
        category: "men",
        subcategory: "pajamas",
        season: "winter",
        price: 29.00,
        originalPrice: 45.00,
        image: "https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?q=80&w=600&auto=format&fit=crop",
        description: "Warm cotton flannel lounge pants featuring a relaxed straight-leg cut and elastic drawstring waist.",
        sizes: ["M", "L", "XL"],
        badge: "Cozy"
    },
    {
        id: 33,
        title: "Men's Active Athletic Hoodie",
        category: "men",
        subcategory: "activewear",
        season: "winter",
        price: 65.00,
        originalPrice: 95.00,
        image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=600&auto=format&fit=crop",
        description: "High-performance moisture-wicking athletic hoodie with front zipper and ergonomic cuffs.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Athletic"
    },
    {
        id: 34,
        title: "Dry-Fit Training Pants",
        category: "men",
        subcategory: "activewear",
        season: "spring",
        price: 45.00,
        originalPrice: 65.00,
        image: "https://images.unsplash.com/photo-1490604001847-b712b0c2f957?q=80&w=600&auto=format&fit=crop",
        description: "Lightweight joggers built for speed and training. Quick-drying and highly breathable.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Performance"
    },
    {
        id: 35,
        title: "Classic Leather Dress Belt",
        category: "men",
        subcategory: "accessories",
        season: "spring",
        price: 35.00,
        originalPrice: 55.00,
        image: "https://images.unsplash.com/photo-1624222247344-550fb8ec5519?q=80&w=600&auto=format&fit=crop",
        description: "Crafted from full-grain vegetable-tanned Italian leather with a solid brass buckle.",
        sizes: ["32", "34", "36", "38"],
        badge: "Essential"
    },
    {
        id: 36,
        title: "Executive Leather Bifold Wallet",
        category: "men",
        subcategory: "accessories",
        season: "spring",
        price: 45.00,
        originalPrice: 75.00,
        image: "https://images.unsplash.com/photo-1627124424040-b3eff5990227?q=80&w=600&auto=format&fit=crop",
        description: "Sleek bifold wallet with RFID protection, 8 card slots, and premium leather lining.",
        sizes: ["Free Size"],
        badge: "Luxury"
    },
    {
        id: 37,
        title: "Italian Handcrafted Derby Shoes",
        category: "men",
        subcategory: "footwear",
        season: "spring",
        price: 159.00,
        originalPrice: 249.00,
        image: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?q=80&w=600&auto=format&fit=crop",
        description: "Classic lace-up Derby shoes in premium calfskin leather with a cushioned leather insole.",
        sizes: ["40", "41", "42", "43", "44"],
        badge: "Premium"
    },
    {
        id: 38,
        title: "Minimalist White Leather Sneakers",
        category: "men",
        subcategory: "footwear",
        season: "summer",
        price: 89.00,
        originalPrice: 139.00,
        image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=600&auto=format&fit=crop",
        description: "Clean, ultra-versatile white leather sneakers designed for smart-casual dress codes.",
        sizes: ["40", "41", "42", "43", "44"],
        badge: "Best Seller"
    },
    {
        id: 39,
        title: "Classic Cotton Crew Socks Set",
        category: "men",
        subcategory: "footwear",
        season: "spring",
        price: 15.00,
        originalPrice: 25.00,
        image: "https://images.unsplash.com/photo-1582966772680-860e372bb558?q=80&w=600&auto=format&fit=crop",
        description: "Pack of 3 combed cotton crew socks with reinforced heels and toes for exceptional comfort.",
        sizes: ["M", "L"],
        badge: "Utility"
    },

    // ==========================================
    // WOMEN (Ladies)
    // ==========================================
    {
        id: 41,
        title: "Botanical Silk Floral Maxi Dress",
        category: "women",
        subcategory: "western-wears",
        season: "summer",
        price: 115.00,
        originalPrice: 175.00,
        image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=600&auto=format&fit=crop",
        description: "Charming botanical print maxi dress with a V-neckline and flowing tiered skirt. Cut from premium lightweight silk blend.",
        sizes: ["XS", "S", "M", "L"],
        badge: "Trending"
    },
    {
        id: 42,
        title: "Satin Pleated Evening Gown",
        category: "women",
        subcategory: "western-wears",
        season: "winter",
        price: 189.00,
        originalPrice: 299.00,
        image: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=600&auto=format&fit=crop",
        description: "Sophisticated evening gown featuring a structured pleated wrap detail and floor-sweeping silhouette.",
        sizes: ["XS", "S", "M", "L"],
        badge: "Elegant Night"
    },
    {
        id: 43,
        title: "Bohemian Midi Sun Dress",
        category: "women",
        subcategory: "western-wears",
        season: "summer",
        price: 79.00,
        originalPrice: 120.00,
        image: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?q=80&w=600&auto=format&fit=crop",
        description: "Light and airy midi dress featuring delicate embroidery and adjustable shoulder straps.",
        sizes: ["XS", "S", "M", "L"],
        badge: "Summer"
    },
    {
        id: 44,
        title: "Tailored Blazer Dress",
        category: "women",
        subcategory: "western-wears",
        season: "spring",
        price: 135.00,
        originalPrice: 199.00,
        image: "https://images.unsplash.com/photo-1539109132381-31a1ecd2d5d6?q=80&w=600&auto=format&fit=crop",
        description: "Sleek double-breasted blazer dress crafted with structured shoulders and gold button accents.",
        sizes: ["XS", "S", "M", "L"],
        badge: "Chic"
    },
    {
        id: 45,
        title: "Pleated Accordion Midi Skirt",
        category: "women",
        subcategory: "western-wears",
        season: "spring",
        price: 65.00,
        originalPrice: 95.00,
        image: "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?q=80&w=600&auto=format&fit=crop",
        description: "Flowing accordion pleated midi skirt with comfortable elastic waist band.",
        sizes: ["XS", "S", "M", "L"],
        badge: "New"
    },
    {
        id: 46,
        title: "Hand-Painted Floral Saree",
        category: "women",
        subcategory: "ethnic",
        season: "summer",
        price: 149.00,
        originalPrice: 220.00,
        image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=600&auto=format&fit=crop",
        description: "Exquisite organza saree featuring hand-painted floral motifs and a delicate gold border.",
        sizes: ["Free Size"],
        badge: "Artisan"
    },
    {
        id: 47,
        title: "Embroidered Anarkali Suit",
        category: "women",
        subcategory: "ethnic",
        season: "winter",
        price: 185.00,
        originalPrice: 280.00,
        image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=600&auto=format&fit=crop",
        description: "Grand Anarkali suit with detailed thread-work and a matching silk dupatta.",
        sizes: ["S", "M", "L", "XL"],
        badge: "Wedding Wear"
    },
    {
        id: 48,
        title: "Pure Silk Banarasi Saree",
        category: "women",
        subcategory: "ethnic",
        season: "winter",
        price: 245.00,
        originalPrice: 380.00,
        image: "https://images.unsplash.com/photo-1610030470298-40899321ef9a?q=80&w=600&auto=format&fit=crop",
        description: "Traditional Banarasi silk saree with authentic silver zari work. A heirloom piece.",
        sizes: ["Free Size"],
        badge: "Premium"
    },
    {
        id: 49,
        title: "Daily Wear Cotton Kurta",
        category: "women",
        subcategory: "ethnic",
        season: "summer",
        price: 45.00,
        originalPrice: 65.00,
        image: "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?q=80&w=600&auto=format&fit=crop",
        description: "Breathable cotton kurta with block prints. Perfect for everyday summer comfort.",
        sizes: ["XS", "S", "M", "L", "XL"],
        badge: "Essential"
    },
    {
        id: 50,
        title: "Mirror-Work Lehenga Choli",
        category: "women",
        subcategory: "ethnic",
        season: "spring",
        price: 210.00,
        originalPrice: 320.00,
        image: "https://images.unsplash.com/photo-1583391733956-6c78276477e2?q=80&w=600&auto=format&fit=crop",
        description: "Vibrant lehenga choli featuring intricate mirror-work and heavy embroidery.",
        sizes: ["S", "M", "L"],
        badge: "Festive"
    },
    {
        id: 51,
        title: "High-Waist Skinny Jeans",
        category: "women",
        subcategory: "jeans",
        season: "spring",
        price: 79.00,
        originalPrice: 119.00,
        image: "https://images.unsplash.com/photo-1551854838-212c50b4c184?q=80&w=600&auto=format&fit=crop",
        description: "Classic blue high-waisted skinny jeans with premium stretch denim comfort.",
        sizes: ["XS", "S", "M", "L"],
        badge: "Must-Have"
    },
    {
        id: 52,
        title: "Wide-Leg Cropped Jeans",
        category: "women",
        subcategory: "jeans",
        season: "summer",
        price: 85.00,
        originalPrice: 125.00,
        image: "https://images.unsplash.com/photo-1604176354204-9268737828e4?q=80&w=600&auto=format&fit=crop",
        description: "Fashionable wide-leg cropped jeans made from sustainable organic denim.",
        sizes: ["S", "M", "L"],
        badge: "Modern"
    },
    {
        id: 53,
        title: "Satin Chemise Sleep Slip",
        category: "women",
        subcategory: "pajamas",
        season: "summer",
        price: 39.00,
        originalPrice: 59.00,
        image: "https://images.unsplash.com/photo-1631857455684-a54a2f03665f?q=80&w=600&auto=format&fit=crop",
        description: "Luxuriously soft satin chemise sleepwear with delicate lace trim details.",
        sizes: ["XS", "S", "M", "L"],
        badge: "Loungewear"
    },
    {
        id: 54,
        title: "Classic Silk Pajama Set",
        category: "women",
        subcategory: "pajamas",
        season: "winter",
        price: 89.00,
        originalPrice: 129.00,
        image: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=600&auto=format&fit=crop",
        description: "Pure mulberry silk long-sleeve pajama top and bottoms for the ultimate night's sleep.",
        sizes: ["S", "M", "L"],
        badge: "Premium"
    },
    {
        id: 55,
        title: "Athletic Leggings & Sports Bra Set",
        category: "women",
        subcategory: "activewear",
        season: "spring",
        price: 69.00,
        originalPrice: 99.00,
        image: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?q=80&w=600&auto=format&fit=crop",
        description: "Matching high-rise compression leggings and supportive sports bra for high-intensity workouts.",
        sizes: ["XS", "S", "M", "L"],
        badge: "Athletic"
    },
    {
        id: 56,
        title: "Trench Belted Long Coat",
        category: "women",
        subcategory: "winter",
        season: "winter",
        price: 199.00,
        originalPrice: 299.00,
        image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=600&auto=format&fit=crop",
        description: "Elegant double-breasted winter trench coat with waist-defining belt and storm flaps.",
        sizes: ["S", "M", "L"],
        badge: "Winter Warmth"
    },
    {
        id: 57,
        title: "Suede Leather Block Heels",
        category: "women",
        subcategory: "footwear",
        season: "spring",
        price: 99.00,
        originalPrice: 149.00,
        image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=600&auto=format&fit=crop",
        description: "Chic open-toe suede heels featuring a supportive block heel and secure ankle strap.",
        sizes: ["36", "37", "38", "39", "40"],
        badge: "Elegant"
    },
    {
        id: 58,
        title: "Classic Saffiano Leather Handbag",
        category: "women",
        subcategory: "accessories",
        season: "spring",
        price: 129.00,
        originalPrice: 199.00,
        image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=600&auto=format&fit=crop",
        description: "Structured handbag made of scratch-resistant Saffiano leather. Multi-compartment interior.",
        sizes: ["Free Size"],
        badge: "Luxury"
    },
    {
        id: 59,
        title: "High-Waist Denim Shorts",
        category: "women",
        subcategory: "shorts",
        season: "summer",
        price: 45.00,
        originalPrice: 69.00,
        image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=600&auto=format&fit=crop",
        description: "Classic light-wash denim shorts with a high-rise waist and frayed hems.",
        sizes: ["XS", "S", "M", "L"],
        badge: "Summer Essential"
    },
    {
        id: 60,
        title: "Double-Breasted Office Blazer",
        category: "women",
        subcategory: "formals",
        season: "spring",
        price: 110.00,
        originalPrice: 169.00,
        image: "https://images.unsplash.com/photo-1548624149-f7b2e650d53f?q=80&w=600&auto=format&fit=crop",
        description: "Sharp and sophisticated office blazer in a breathable linen-cotton blend.",
        sizes: ["XS", "S", "M", "L", "XL"],
        badge: "Workwear"
    },
    {
        id: 61,
        title: "Ribbed Crewneck Casual Tee",
        category: "women",
        subcategory: "casuals",
        season: "summer",
        price: 25.00,
        originalPrice: 39.00,
        image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=600&auto=format&fit=crop",
        description: "Super soft, slim-fit ribbed cotton t-shirt with classic crew neck.",
        sizes: ["XS", "S", "M", "L"],
        badge: "Basics"
    },

    // ==========================================
    // KIDS (Little Ones)
    // ==========================================
    {
        id: 71,
        title: "Boys Formal Tuxedo Set",
        category: "kids",
        subcategory: "formals",
        season: "winter",
        price: 65.00,
        originalPrice: 95.00,
        image: "https://images.unsplash.com/photo-1519457431-44ccd64a579b?q=80&w=600&auto=format&fit=crop",
        description: "Dapper tuxedo set for little gentlemen. Includes jacket, shirt, and trousers.",
        sizes: ["4Y", "6Y", "8Y", "10Y"],
        badge: "Best Seller"
    },
    {
        id: 72,
        title: "Girls Sparkle Party Dress",
        category: "kids",
        subcategory: "formals",
        season: "spring",
        price: 55.00,
        originalPrice: 80.00,
        image: "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?q=80&w=600&auto=format&fit=crop",
        description: "Charming party dress with sequins and a layered tulle skirt for special days.",
        sizes: ["2Y", "4Y", "6Y", "8Y"],
        badge: "Celebration"
    },
    {
        id: 73,
        title: "Kids Stretch Overalls",
        category: "kids",
        subcategory: "jeans",
        season: "summer",
        price: 35.00,
        originalPrice: 55.00,
        image: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=600&auto=format&fit=crop",
        description: "Soft stretch denim overalls designed for active play and easy movements.",
        sizes: ["2Y", "4Y", "6Y"],
        badge: "Play Ready"
    },
    {
        id: 74,
        title: "Boys Cargo Shorts",
        category: "kids",
        subcategory: "shorts",
        season: "summer",
        price: 28.00,
        originalPrice: 42.00,
        image: "https://images.unsplash.com/photo-1622295083720-ff9bcd96e0ac?q=80&w=600&auto=format&fit=crop",
        description: "Rugged cargo shorts with multiple pockets for all their small treasures.",
        sizes: ["4Y", "6Y", "8Y", "10Y"],
        badge: "Durable"
    },
    {
        id: 75,
        title: "Girls Denim Skirt",
        category: "kids",
        subcategory: "jeans",
        season: "summer",
        price: 32.00,
        originalPrice: 48.00,
        image: "https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=600&auto=format&fit=crop",
        description: "Classic denim skirt with an adjustable waistband for the perfect fit.",
        sizes: ["3Y", "5Y", "7Y"],
        badge: "New"
    },
    {
        id: 76,
        title: "Kids Cozy Fleece Pajamas",
        category: "kids",
        subcategory: "pajamas",
        season: "winter",
        price: 29.00,
        originalPrice: 45.00,
        image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=600&auto=format&fit=crop",
        description: "Super soft microfleece pajama set to keep them warm all through the night.",
        sizes: ["2Y", "4Y", "6Y", "8Y"],
        badge: "Warm Wear"
    },
    {
        id: 77,
        title: "Kids Cotton Nightshirt",
        category: "kids",
        subcategory: "pajamas",
        season: "summer",
        price: 22.00,
        originalPrice: 32.00,
        image: "https://images.unsplash.com/photo-1540479859555-17af45c78a62?q=80&w=600&auto=format&fit=crop",
        description: "Breathable organic cotton nightshirt with cheerful bedtime illustrations.",
        sizes: ["3Y", "5Y", "7Y"],
        badge: "Comfort"
    },
    {
        id: 78,
        title: "Kids Animal Graphic T-Shirt",
        category: "kids",
        subcategory: "casuals",
        season: "summer",
        price: 19.00,
        originalPrice: 29.00,
        image: "https://images.unsplash.com/photo-1607990283143-e81e7a2c93ab?q=80&w=600&auto=format&fit=crop",
        description: "Fun graphic tee featuring friendly animals and vibrant nontoxic prints.",
        sizes: ["2Y", "4Y", "6Y", "8Y"],
        badge: "Play"
    },
    {
        id: 79,
        title: "Kids Light-Up Sneakers",
        category: "kids",
        subcategory: "footwear",
        season: "spring",
        price: 39.00,
        originalPrice: 59.00,
        image: "https://images.unsplash.com/photo-1514989940753-e8d750596716?q=80&w=600&auto=format&fit=crop",
        description: "Active light-up sneakers with velcro straps for easy independent wear.",
        sizes: ["26", "28", "30", "32"],
        badge: "Fun"
    },
    {
        id: 80,
        title: "Kids School Leather Shoes",
        category: "kids",
        subcategory: "footwear",
        season: "spring",
        price: 45.00,
        originalPrice: 65.00,
        image: "https://images.unsplash.com/photo-1603798125914-7b5d27789248?q=80&w=600&auto=format&fit=crop",
        description: "Polished leather school shoes with durable soles and supportive arch.",
        sizes: ["27", "29", "31", "33"],
        badge: "School"
    },
    {
        id: 81,
        title: "Kids Athletic Running Tracksuit",
        category: "kids",
        subcategory: "activewear",
        season: "spring",
        price: 49.00,
        originalPrice: 69.00,
        image: "https://images.unsplash.com/photo-1471286174243-e7a4d9ab6ce9?q=80&w=600&auto=format&fit=crop",
        description: "Comfortable kids tracksuit for gym class, sports practice, or playground fun.",
        sizes: ["4Y", "6Y", "8Y", "10Y"],
        badge: "Active"
    },
    {
        id: 82,
        title: "Kids Knit Cardigan Sweater",
        category: "kids",
        subcategory: "winter",
        season: "winter",
        price: 39.00,
        originalPrice: 59.00,
        image: "https://images.unsplash.com/photo-1515488042361-404e9250afef?q=80&w=600&auto=format&fit=crop",
        description: "Thick, warm cotton-knit cardigan sweater featuring kid-friendly buttons and front pockets.",
        sizes: ["3Y", "4Y", "5Y", "6Y", "8Y"],
        badge: "Cozy"
    },
    {
        id: 83,
        title: "Kids Ethnic Kurta Pajama Set",
        category: "kids",
        subcategory: "ethnic",
        season: "spring",
        price: 45.00,
        originalPrice: 69.00,
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600&auto=format&fit=crop",
        description: "Vibrant ethnic kurta set for festive occasions and family celebrations.",
        sizes: ["2Y", "4Y", "6Y", "8Y"],
        badge: "Festive"
    },
    {
        id: 84,
        title: "Kids Cotton Canvas Cap",
        category: "kids",
        subcategory: "accessories",
        season: "summer",
        price: 15.00,
        originalPrice: 22.00,
        image: "https://images.unsplash.com/photo-1618517047940-a79ffad093eb?q=80&w=600&auto=format&fit=crop",
        description: "Adjustable cotton canvas baseball cap to keep the sun off their eyes during play.",
        sizes: ["Free Size"],
        badge: "Essential"
    }
];

// Helper to find a product by ID
function getProductById(id) {
    return products.find(p => p.id === parseInt(id));
}
